import type { BankQuestion, QuestionType } from './types'

const choice = (
  id: string,
  type: QuestionType,
  prompt: string,
  context: string,
  options: Array<[string, string]>,
  answer: string,
  explanation: string,
  theme: string,
  tags: string[],
  errorReason: string,
): BankQuestion => ({
  id,
  bankQuestionId: id,
  type,
  prompt,
  context,
  inputMode: 'choice',
  options: options.map(([optionId, label]) => ({ id: optionId, label })),
  standardAnswer: answer,
  acceptableAnswers: [answer],
  explanation,
  theme,
  difficulty: 'C1',
  tags,
  source: '高阶词汇与短语',
  errorReason,
})

const text = (
  id: string,
  type: QuestionType,
  prompt: string,
  context: string,
  answer: string,
  acceptableAnswers: string[],
  explanation: string,
  theme: string,
  tags: string[],
  errorReason: string,
): BankQuestion => ({
  id,
  bankQuestionId: id,
  type,
  prompt,
  context,
  inputMode: 'text',
  standardAnswer: answer,
  acceptableAnswers,
  explanation,
  theme,
  difficulty: 'C1',
  tags,
  source: '高阶词汇与短语',
  errorReason,
})

export const questionBank: BankQuestion[] = [
  choice(
    'ctx-resilient',
    'context_translation',
    '结合语境，选择 resilient 最贴切的中文含义。',
    'Despite repeated funding cuts, the community library proved remarkably resilient.',
    [
      ['a', '有韧性且能恢复的'],
      ['b', '昂贵而罕见的'],
      ['c', '过度依赖的'],
      ['d', '短暂无效的'],
    ],
    'a',
    'resilient 强调承受冲击后恢复或适应的能力。',
    '城市与社区',
    ['语境', '形容词'],
    'meaning_confusion',
  ),
  choice(
    'ctx-compelling',
    'context_translation',
    '结合语境，选择 compelling 最贴切的中文含义。',
    'The report presents compelling evidence that early intervention reduces long-term costs.',
    [
      ['a', '含糊的'],
      ['b', '令人信服的'],
      ['c', '未经证实的'],
      ['d', '相互矛盾的'],
    ],
    'b',
    'compelling evidence 指强有力、令人信服的证据。',
    '教育与研究',
    ['语境', '学术词汇'],
    'meaning_confusion',
  ),
  choice(
    'ctx-marginal',
    'context_translation',
    '结合语境，选择 marginal 最贴切的中文含义。',
    'The new policy produced only a marginal improvement in air quality.',
    [
      ['a', '根本性的'],
      ['b', '难以测量的'],
      ['c', '轻微的'],
      ['d', '永久的'],
    ],
    'c',
    'marginal 在此表示幅度很小、处于边缘水平。',
    '环境',
    ['语境', '程度'],
    'meaning_confusion',
  ),
  choice(
    'ctx-viable',
    'context_translation',
    '结合语境，选择 viable 最贴切的中文含义。',
    'Remote work is not a viable option for every occupation.',
    [
      ['a', '切实可行的'],
      ['b', '法律禁止的'],
      ['c', '高度理想化的'],
      ['d', '短期流行的'],
    ],
    'a',
    'viable option 指现实条件下可实施并能持续的选择。',
    '工作',
    ['语境', '形容词'],
    'meaning_confusion',
  ),

  text(
    'spell-allocate',
    'spelling',
    '根据中文提示拼写目标词。',
    '为特定目的分配（资源、资金或时间）',
    'allocate',
    ['allocate'],
    'allocate 常与 resources、funding、time 搭配。',
    '工作',
    ['拼写', '动词'],
    'spelling_error',
  ),
  text(
    'spell-deteriorate',
    'spelling',
    '根据中文提示拼写目标词。',
    '逐渐恶化；变坏',
    'deteriorate',
    ['deteriorate'],
    'deteriorate 是不及物动词，常描述环境、健康或关系恶化。',
    '健康',
    ['拼写', '动词'],
    'spelling_error',
  ),
  text(
    'spell-inevitable',
    'spelling',
    '根据中文提示拼写目标词。',
    '不可避免的',
    'inevitable',
    ['inevitable'],
    '注意中间为 -evit-，常见结构是 it is inevitable that…',
    '科技',
    ['拼写', '形容词'],
    'spelling_error',
  ),
  text(
    'spell-sustainable',
    'spelling',
    '根据中文提示拼写目标词。',
    '可持续的',
    'sustainable',
    ['sustainable'],
    'sustainable development 是环境与城市议题中的高频搭配。',
    '环境',
    ['拼写', '形容词'],
    'spelling_error',
  ),

  text(
    'cloze-mitigate',
    'cloze',
    '用一个词完成句子。',
    'Targeted subsidies may ______ the impact of rising energy prices on low-income households.',
    'mitigate',
    ['mitigate', 'lessen'],
    'mitigate the impact 表示减轻影响；lessen 也可接受。',
    '经济与社会',
    ['完形', '动词搭配'],
    'incomplete_answer',
  ),
  text(
    'cloze-foster',
    'cloze',
    '用一个词完成句子。',
    'Well-designed public spaces can ______ a stronger sense of community.',
    'foster',
    ['foster', 'promote'],
    'foster a sense of community 表示培育社区归属感。',
    '城市与社区',
    ['完形', '动词搭配'],
    'incomplete_answer',
  ),
  text(
    'cloze-undermine',
    'cloze',
    '用一个词完成句子。',
    'A lack of transparency can ______ public trust in institutions.',
    'undermine',
    ['undermine', 'erode'],
    'undermine 或 erode public trust 都表示削弱公众信任。',
    '文化与社会',
    ['完形', '学术表达'],
    'incomplete_answer',
  ),
  text(
    'cloze-outweigh',
    'cloze',
    '用一个词完成句子。',
    'For many commuters, the benefits of flexibility ______ the minor inconvenience.',
    'outweigh',
    ['outweigh'],
    'A outweighs B 表示 A 的重要性或好处超过 B。',
    '工作',
    ['完形', '比较'],
    'incomplete_answer',
  ),

  choice(
    'collocation-draw-conclusion',
    'collocation_choice',
    '选择最自然的搭配。',
    'The researchers were reluctant to ___ a firm conclusion from the limited sample.',
    [
      ['a', 'draw'],
      ['b', 'pull'],
      ['c', 'build'],
      ['d', 'carry'],
    ],
    'a',
    'draw a conclusion 是固定搭配。',
    '教育与研究',
    ['搭配', '学术写作'],
    'collocation_confusion',
  ),
  choice(
    'collocation-pose-threat',
    'collocation_choice',
    '选择最自然的搭配。',
    'Untreated industrial waste may ___ a serious threat to marine ecosystems.',
    [
      ['a', 'make'],
      ['b', 'pose'],
      ['c', 'set'],
      ['d', 'give'],
    ],
    'b',
    'pose a threat/risk/challenge 是正式写作常用搭配。',
    '环境',
    ['搭配', '风险'],
    'collocation_confusion',
  ),
  choice(
    'collocation-address-concern',
    'collocation_choice',
    '选择最自然的搭配。',
    'The revised proposal attempts to ___ residents’ concerns about noise.',
    [
      ['a', 'answer to'],
      ['b', 'address'],
      ['c', 'settle with'],
      ['d', 'reply'],
    ],
    'b',
    'address concerns 指认真处理或回应关切。',
    '城市与社区',
    ['搭配', '正式表达'],
    'collocation_confusion',
  ),
  choice(
    'collocation-play-role',
    'collocation_choice',
    '选择最自然的搭配。',
    'Family expectations can ___ a decisive role in career choices.',
    [
      ['a', 'do'],
      ['b', 'hold'],
      ['c', 'play'],
      ['d', 'perform'],
    ],
    'c',
    'play a role in 是固定搭配。',
    '工作',
    ['搭配', '论证'],
    'collocation_confusion',
  ),

  choice(
    'phrase-strike-balance',
    'phrase_meaning',
    '选择短语 strike a balance 的准确含义。',
    'Cities must strike a balance between economic growth and environmental protection.',
    [
      ['a', '在不同需求之间取得平衡'],
      ['b', '取消两个目标'],
      ['c', '优先追求经济增长'],
      ['d', '把决定推迟'],
    ],
    'a',
    'strike a balance between A and B 表示兼顾两者。',
    '环境',
    ['短语', '论证'],
    'meaning_confusion',
  ),
  choice(
    'phrase-long-run',
    'phrase_meaning',
    '选择短语 in the long run 的准确含义。',
    'Preventive healthcare may be costly initially but saves money in the long run.',
    [
      ['a', '立即'],
      ['b', '从长远来看'],
      ['c', '在紧急情况下'],
      ['d', '偶尔'],
    ],
    'b',
    'in the long run 用于讨论长期结果。',
    '健康',
    ['短语', '时间框架'],
    'meaning_confusion',
  ),
  choice(
    'phrase-at-odds',
    'phrase_meaning',
    '选择短语 be at odds with 的准确含义。',
    'The advertising campaign is at odds with the company’s sustainability pledge.',
    [
      ['a', '与……一致'],
      ['b', '取决于……'],
      ['c', '与……冲突'],
      ['d', '补充……'],
    ],
    'c',
    'be at odds with 表示与某事不一致或相冲突。',
    '文化与社会',
    ['短语', '对比'],
    'meaning_confusion',
  ),
  choice(
    'phrase-pave-way',
    'phrase_meaning',
    '选择短语 pave the way for 的准确含义。',
    'Reliable digital infrastructure can pave the way for broader access to education.',
    [
      ['a', '阻碍'],
      ['b', '为……创造条件'],
      ['c', '衡量'],
      ['d', '取代'],
    ],
    'b',
    'pave the way for 表示为后续发展铺平道路。',
    '科技',
    ['短语', '因果'],
    'meaning_confusion',
  ),
]

export function getBankQuestion(id: string): BankQuestion | undefined {
  return questionBank.find((question) => question.id === id)
}
