import type { BankQuestion, QuestionType } from './types'

function optionReason(
  type: QuestionType,
  label: string,
  correct: boolean,
  explanation: string,
): string {
  if (correct) return `该选项符合句意和考查点。${explanation}`
  if (type === 'context_translation') {
    return `“${label}”与句中给出的结果、程度或态度不一致，可由上下文排除。`
  }
  if (type === 'phrase_meaning') {
    return `“${label}”没有表达该短语在句中的实际功能或语气，可排除。`
  }
  return `“${label}”不能同时满足空格前后的语法结构、词义和自然搭配，可排除。`
}

const optionMeaningsZh: Record<string, string> = {
  mitigate: '减轻；缓和',
  intensify: '加强；加剧',
  allocate: '分配；拨给',
  predict: '预测；预言',
  foster: '促进；培养',
  interrupt: '打断；中断',
  estimate: '估计；评估',
  withdraw: '撤回；退出',
  undermine: '逐渐削弱；损害',
  restore: '恢复；修复',
  measure: '衡量；测量',
  publish: '出版；公布',
  outweigh: '比……更重要；超过',
  postpone: '推迟；延期',
  resemble: '与……相似',
  divide: '分开；划分',
  draw: '得出；拉；画',
  pull: '拉；拖',
  build: '建造；建立',
  carry: '携带；承担',
  make: '制造；使得',
  pose: '造成；构成',
  set: '设置；放置',
  give: '给；提供',
  'answer to': '回应；对……负责',
  address: '处理；回应',
  'settle with': '与……解决；和解',
  reply: '回答；回复',
  do: '做；执行',
  hold: '持有；保持',
  play: '发挥；扮演',
  perform: '执行；表演',
  prolong: '延长；拖延',
  'de-escalate': '缓和；降低冲突强度',
  document: '记录；为……提供文件证明',
  categorise: '分类；归类',
  restorative: '恢复精力的；有修复作用的',
  repairing: '修理中的；用于修理的',
  recoverable: '可恢复的；可挽回的',
  restored: '已恢复的；修复后的',
  clarify: '澄清；阐明',
  justify: '证明……合理；为……辩护',
  impair: '损害；削弱',
  confirm: '确认；证实',
  manufacture: '制造；生产',
  operate: '操作；经营',
  accessible: '可进入的；易使用或理解的',
  optional: '可选择的；非强制的',
  temporary: '暂时的；临时的',
  exclusive: '专属的；排他的',
}

const optionOriginalsEn: Record<string, string> = {
  有韧性且能恢复的: 'resilient',
  昂贵而罕见的: 'costly and rare',
  过度依赖的: 'overly dependent',
  短暂无效的: 'temporarily ineffective',
  含糊的: 'ambiguous',
  令人信服的: 'compelling',
  未经证实的: 'unverified',
  相互矛盾的: 'contradictory',
  根本性的: 'fundamental',
  难以测量的: 'hard to measure',
  轻微的: 'marginal',
  永久的: 'permanent',
  切实可行的: 'viable',
  法律禁止的: 'legally prohibited',
  高度理想化的: 'highly idealised',
  短期流行的: 'temporarily popular',
  在不同需求之间取得平衡: 'strike a balance',
  取消两个目标: 'abandon both goals',
  优先追求经济增长: 'prioritise economic growth',
  把决定推迟: 'postpone the decision',
  立即: 'immediately',
  从长远来看: 'in the long run',
  在紧急情况下: 'in an emergency',
  偶尔: 'occasionally',
  '与……一致': 'be consistent with',
  '取决于……': 'depend on',
  '与……冲突': 'be at odds with',
  '补充……': 'complement',
  阻碍: 'hinder',
  '为……创造条件': 'pave the way for',
  衡量: 'measure',
  取代: 'replace',
  坦率而诚实的: 'candid',
  含蓄且模糊的: 'reserved and vague',
  已经过时的: 'outdated',
  带有敌意的: 'hostile',
  运行缓慢的: 'slow-running',
  不透明且难以理解的: 'opaque',
  完全开放的: 'fully transparent',
  高度准确的: 'highly accurate',
  保有自主选择和行动能力: 'retain agency',
  把决定完全交给系统: 'cede control to the system',
  隐藏自己的身份: 'hide one’s identity',
  提高网络速度: 'increase network speed',
}

function optionMeaningZh(label: string): string {
  if (/\p{Script=Han}/u.test(label)) return label
  const meaning = optionMeaningsZh[label]
  if (!meaning) throw new Error(`Missing Chinese option meaning: ${label}`)
  return meaning
}

function optionOriginalText(label: string): string {
  if (!/\p{Script=Han}/u.test(label)) return label
  const original = optionOriginalsEn[label]
  if (!original) throw new Error(`Missing original English option: ${label}`)
  return original
}

const choice = (
  id: string,
  type: QuestionType,
  prompt: string,
  context: string,
  options: Array<[string, string]>,
  answer: string,
  explanation: string,
  theme: string,
  tags: string[],
  errorReason: string,
): BankQuestion => ({
  id,
  bankQuestionId: id,
  type,
  prompt,
  context,
  inputMode: 'choice',
  options: options.map(([optionId, label]) => ({ id: optionId, label })),
  standardAnswer: answer,
  acceptableAnswers: [answer],
  explanation,
  answerAnalysis: {
    reasoning: `先看空格前后的语法结构，再核对语境和固定搭配。${explanation}`,
    optionReasons: Object.fromEntries(
      options.map(([optionId, label]) => [
        optionId,
        optionReason(type, label, optionId === answer, explanation),
      ]),
    ),
    optionMeanings: Object.fromEntries(
      options.map(([optionId, label]) => [optionId, optionMeaningZh(label)]),
    ),
    optionOriginals: Object.fromEntries(
      options.map(([optionId, label]) => [optionId, optionOriginalText(label)]),
    ),
  },
  theme,
  difficulty: 'C1',
  tags,
  source: '高阶词汇与短语',
  errorReason,
})

const text = (
  id: string,
  type: QuestionType,
  prompt: string,
  context: string,
  answer: string,
  acceptableAnswers: string[],
  explanation: string,
  theme: string,
  tags: string[],
  errorReason: string,
): BankQuestion => ({
  id,
  bankQuestionId: id,
  type,
  prompt,
  context,
  inputMode: 'text',
  standardAnswer: answer,
  acceptableAnswers,
  explanation,
  answerAnalysis: {
    reasoning: `先根据中文提示确定词义和词性，再检查拼写与句中形式。${explanation}`,
  },
  theme,
  difficulty: 'C1',
  tags,
  source: '高阶词汇与短语',
  errorReason,
})

export const questionBank: BankQuestion[] = [
  choice(
    'ctx-resilient',
    'context_translation',
    '结合语境，选择 resilient 最贴切的中文含义。',
    'Despite repeated funding cuts, the community library proved remarkably resilient.',
    [
      ['a', '有韧性且能恢复的'],
      ['b', '昂贵而罕见的'],
      ['c', '过度依赖的'],
      ['d', '短暂无效的'],
    ],
    'a',
    'resilient 强调承受冲击后恢复或适应的能力。',
    '城市与社区',
    ['语境', '形容词'],
    'meaning_confusion',
  ),
  choice(
    'ctx-compelling',
    'context_translation',
    '结合语境，选择 compelling 最贴切的中文含义。',
    'The report presents compelling evidence that early intervention reduces long-term costs.',
    [
      ['a', '含糊的'],
      ['b', '令人信服的'],
      ['c', '未经证实的'],
      ['d', '相互矛盾的'],
    ],
    'b',
    'compelling evidence 指强有力、令人信服的证据。',
    '教育与研究',
    ['语境', '学术词汇'],
    'meaning_confusion',
  ),
  choice(
    'ctx-marginal',
    'context_translation',
    '结合语境，选择 marginal 最贴切的中文含义。',
    'The new policy produced only a marginal improvement in air quality.',
    [
      ['a', '根本性的'],
      ['b', '难以测量的'],
      ['c', '轻微的'],
      ['d', '永久的'],
    ],
    'c',
    'marginal 在此表示幅度很小、处于边缘水平。',
    '环境',
    ['语境', '程度'],
    'meaning_confusion',
  ),
  choice(
    'ctx-viable',
    'context_translation',
    '结合语境，选择 viable 最贴切的中文含义。',
    'Remote work is not a viable option for every occupation.',
    [
      ['a', '切实可行的'],
      ['b', '法律禁止的'],
      ['c', '高度理想化的'],
      ['d', '短期流行的'],
    ],
    'a',
    'viable option 指现实条件下可实施并能持续的选择。',
    '工作',
    ['语境', '形容词'],
    'meaning_confusion',
  ),

  text(
    'spell-allocate',
    'spelling',
    '根据中文提示拼写目标词。',
    '为特定目的分配（资源、资金或时间）',
    'allocate',
    ['allocate'],
    'allocate 常与 resources、funding、time 搭配。',
    '工作',
    ['拼写', '动词'],
    'spelling_error',
  ),
  text(
    'spell-deteriorate',
    'spelling',
    '根据中文提示拼写目标词。',
    '逐渐恶化；变坏',
    'deteriorate',
    ['deteriorate'],
    'deteriorate 是不及物动词，常描述环境、健康或关系恶化。',
    '健康',
    ['拼写', '动词'],
    'spelling_error',
  ),
  text(
    'spell-inevitable',
    'spelling',
    '根据中文提示拼写目标词。',
    '不可避免的',
    'inevitable',
    ['inevitable'],
    '注意中间为 -evit-，常见结构是 it is inevitable that…',
    '科技',
    ['拼写', '形容词'],
    'spelling_error',
  ),
  text(
    'spell-sustainable',
    'spelling',
    '根据中文提示拼写目标词。',
    '可持续的',
    'sustainable',
    ['sustainable'],
    'sustainable development 是环境与城市议题中的高频搭配。',
    '环境',
    ['拼写', '形容词'],
    'spelling_error',
  ),

  choice(
    'cloze-mitigate',
    'cloze',
    '选择最适合填入空格的词。',
    'Targeted subsidies may ______ the impact of rising energy prices on low-income households.',
    [
      ['a', 'mitigate'],
      ['b', 'intensify'],
      ['c', 'allocate'],
      ['d', 'predict'],
    ],
    'a',
    'mitigate the impact 是自然搭配，表示“减轻影响”。',
    '经济与社会',
    ['完形', '动词搭配'],
    'incomplete_answer',
  ),
  choice(
    'cloze-foster',
    'cloze',
    '选择最适合填入空格的词。',
    'Well-designed public spaces can ______ a stronger sense of community.',
    [
      ['a', 'foster'],
      ['b', 'interrupt'],
      ['c', 'estimate'],
      ['d', 'withdraw'],
    ],
    'a',
    'foster a sense of community 表示培育社区归属感。',
    '城市与社区',
    ['完形', '动词搭配'],
    'incomplete_answer',
  ),
  choice(
    'cloze-undermine',
    'cloze',
    '选择最适合填入空格的词。',
    'A lack of transparency can ______ public trust in institutions.',
    [
      ['a', 'restore'],
      ['b', 'undermine'],
      ['c', 'measure'],
      ['d', 'publish'],
    ],
    'b',
    'undermine public trust 表示逐步削弱公众信任。',
    '文化与社会',
    ['完形', '学术表达'],
    'incomplete_answer',
  ),
  choice(
    'cloze-outweigh',
    'cloze',
    '选择最适合填入空格的词。',
    'For many commuters, the benefits of flexibility ______ the minor inconvenience.',
    [
      ['a', 'outweigh'],
      ['b', 'postpone'],
      ['c', 'resemble'],
      ['d', 'divide'],
    ],
    'a',
    'A outweighs B 表示 A 的重要性或好处超过 B。',
    '工作',
    ['完形', '比较'],
    'incomplete_answer',
  ),

  choice(
    'collocation-draw-conclusion',
    'collocation_choice',
    '选择最自然的搭配。',
    'The researchers were reluctant to ___ a firm conclusion from the limited sample.',
    [
      ['a', 'draw'],
      ['b', 'pull'],
      ['c', 'build'],
      ['d', 'carry'],
    ],
    'a',
    'draw a conclusion 是固定搭配。',
    '教育与研究',
    ['搭配', '学术写作'],
    'collocation_confusion',
  ),
  choice(
    'collocation-pose-threat',
    'collocation_choice',
    '选择最自然的搭配。',
    'Untreated industrial waste may ___ a serious threat to marine ecosystems.',
    [
      ['a', 'make'],
      ['b', 'pose'],
      ['c', 'set'],
      ['d', 'give'],
    ],
    'b',
    'pose a threat/risk/challenge 是正式写作常用搭配。',
    '环境',
    ['搭配', '风险'],
    'collocation_confusion',
  ),
  choice(
    'collocation-address-concern',
    'collocation_choice',
    '选择最自然的搭配。',
    'The revised proposal attempts to ___ residents’ concerns about noise.',
    [
      ['a', 'answer to'],
      ['b', 'address'],
      ['c', 'settle with'],
      ['d', 'reply'],
    ],
    'b',
    'address concerns 指认真处理或回应关切。',
    '城市与社区',
    ['搭配', '正式表达'],
    'collocation_confusion',
  ),
  choice(
    'collocation-play-role',
    'collocation_choice',
    '选择最自然的搭配。',
    'Family expectations can ___ a decisive role in career choices.',
    [
      ['a', 'do'],
      ['b', 'hold'],
      ['c', 'play'],
      ['d', 'perform'],
    ],
    'c',
    'play a role in 是固定搭配。',
    '工作',
    ['搭配', '论证'],
    'collocation_confusion',
  ),

  choice(
    'phrase-strike-balance',
    'phrase_meaning',
    '选择短语 strike a balance 的准确含义。',
    'Cities must strike a balance between economic growth and environmental protection.',
    [
      ['a', '在不同需求之间取得平衡'],
      ['b', '取消两个目标'],
      ['c', '优先追求经济增长'],
      ['d', '把决定推迟'],
    ],
    'a',
    'strike a balance between A and B 表示兼顾两者。',
    '环境',
    ['短语', '论证'],
    'meaning_confusion',
  ),
  choice(
    'phrase-long-run',
    'phrase_meaning',
    '选择短语 in the long run 的准确含义。',
    'Preventive healthcare may be costly initially but saves money in the long run.',
    [
      ['a', '立即'],
      ['b', '从长远来看'],
      ['c', '在紧急情况下'],
      ['d', '偶尔'],
    ],
    'b',
    'in the long run 用于讨论长期结果。',
    '健康',
    ['短语', '时间框架'],
    'meaning_confusion',
  ),
  choice(
    'phrase-at-odds',
    'phrase_meaning',
    '选择短语 be at odds with 的准确含义。',
    'The advertising campaign is at odds with the company’s sustainability pledge.',
    [
      ['a', '与……一致'],
      ['b', '取决于……'],
      ['c', '与……冲突'],
      ['d', '补充……'],
    ],
    'c',
    'be at odds with 表示与某事不一致或相冲突。',
    '文化与社会',
    ['短语', '对比'],
    'meaning_confusion',
  ),
  choice(
    'phrase-pave-way',
    'phrase_meaning',
    '选择短语 pave the way for 的准确含义。',
    'Reliable digital infrastructure can pave the way for broader access to education.',
    [
      ['a', '阻碍'],
      ['b', '为……创造条件'],
      ['c', '衡量'],
      ['d', '取代'],
    ],
    'b',
    'pave the way for 表示为后续发展铺平道路。',
    '科技',
    ['短语', '因果'],
    'meaning_confusion',
  ),
  choice(
    'ctx-candid',
    'context_translation',
    '结合语境，选择 candid 最贴切的中文含义。',
    'The manager invited candid feedback before committing the team to an expensive redesign.',
    [
      ['a', '坦率而诚实的'],
      ['b', '含蓄且模糊的'],
      ['c', '已经过时的'],
      ['d', '带有敌意的'],
    ],
    'a',
    'candid 强调不隐瞒真实看法的坦率表达，本身不等于无礼。',
    '工作',
    ['语境', '形容词'],
    'meaning_confusion',
  ),
  text(
    'spell-tentatively',
    'spelling',
    '根据中文提示拼写单词：试探性地；谨慎而尚未确定地。',
    'She ___ proposed a smaller pilot before the full launch.',
    'tentatively',
    ['tentatively'],
    'tentatively 是副词，常修饰 suggest、propose 或 agree。',
    '工作',
    ['拼写', '副词'],
    'spelling_error',
  ),
  choice(
    'cloze-de-escalate',
    'cloze',
    '选择能表达“缓和冲突”的词。',
    'A neutral facilitator can help ___ the dispute before positions harden.',
    [
      ['a', 'prolong'],
      ['b', 'de-escalate'],
      ['c', 'document'],
      ['d', 'categorise'],
    ],
    'b',
    'de-escalate 表示降低冲突、危险或紧张局面的强度。',
    '工作',
    ['完形', '冲突管理'],
    'word_form_error',
  ),
  choice(
    'collocation-restorative-sleep',
    'collocation_choice',
    '选择最自然的搭配。',
    'A quiet routine can support ___ sleep after a demanding day.',
    [
      ['a', 'restorative'],
      ['b', 'repairing'],
      ['c', 'recoverable'],
      ['d', 'restored'],
    ],
    'a',
    'restorative sleep 是常见搭配，指有助于恢复身心状态的睡眠。',
    '健康',
    ['搭配', '形容词'],
    'collocation_confusion',
  ),
  choice(
    'cloze-impair',
    'cloze',
    '选择能表达“损害判断力”的动词。',
    'Severe fatigue can ___ judgement even when a person feels confident.',
    [
      ['a', 'clarify'],
      ['b', 'justify'],
      ['c', 'impair'],
      ['d', 'confirm'],
    ],
    'c',
    'impair judgement/vision/memory 表示削弱某项能力或功能。',
    '健康',
    ['完形', '动词搭配'],
    'word_form_error',
  ),
  choice(
    'ctx-opaque',
    'context_translation',
    '结合语境，选择 opaque 最贴切的中文含义。',
    'Users challenged the platform because its recommendation process remained opaque.',
    [
      ['a', '运行缓慢的'],
      ['b', '不透明且难以理解的'],
      ['c', '完全开放的'],
      ['d', '高度准确的'],
    ],
    'b',
    'opaque 可描述规则、流程或解释不透明，导致外部人员难以理解。',
    '科技',
    ['语境', '形容词'],
    'meaning_confusion',
  ),
  choice(
    'phrase-retain-agency',
    'phrase_meaning',
    '选择短语 retain agency 的准确含义。',
    'Clear controls help users retain agency over what they see online.',
    [
      ['a', '保有自主选择和行动能力'],
      ['b', '把决定完全交给系统'],
      ['c', '隐藏自己的身份'],
      ['d', '提高网络速度'],
    ],
    'a',
    'agency 在此指独立作出选择并采取行动的能力。',
    '科技',
    ['短语', '抽象名词'],
    'meaning_confusion',
  ),
  text(
    'spell-convivial',
    'spelling',
    '根据中文提示拼写单词：欢乐友好的；适合轻松社交的。',
    'The shared kitchen has a warm and ___ atmosphere.',
    'convivial',
    ['convivial'],
    'convivial 常描述聚会、空间或气氛友好而愉快。',
    '城市与社区',
    ['拼写', '形容词'],
    'spelling_error',
  ),
  choice(
    'collocation-foster-trust',
    'collocation_choice',
    '选择最自然的搭配。',
    'Regular face-to-face contact can ___ trust among neighbours.',
    [
      ['a', 'foster'],
      ['b', 'manufacture'],
      ['c', 'operate'],
      ['d', 'perform'],
    ],
    'a',
    'foster trust/cooperation/development 表示促进某种关系或品质逐渐形成。',
    '城市与社区',
    ['搭配', '动词'],
    'collocation_confusion',
  ),
  choice(
    'cloze-accessible',
    'cloze',
    '选择能表达“所有居民都容易使用”的形容词。',
    'Public services should remain ___ to residents with different mobility needs.',
    [
      ['a', 'optional'],
      ['b', 'accessible'],
      ['c', 'temporary'],
      ['d', 'exclusive'],
    ],
    'b',
    'accessible to somebody 表示某人容易到达、使用或理解某事物。',
    '城市与社区',
    ['完形', '形容词搭配'],
    'preposition_error',
  ),
]

export function getBankQuestion(id: string): BankQuestion | undefined {
  return questionBank.find((question) => question.id === id)
}
